### ISSUE TITLE
Whisper to influxdb migration and configuration tools?

### ISSUE THREAD

**Issue by toni-moreno** [vimeo/graphite-influxdb#25]
Hi.

We are working now on a big graphite platform but we have plans to grow a lot the number of systems /products sending metrics in next months / years  and we need something more scalable and also as flexible as whisper is.

We are now testing graphite-influxdb and it seems to be working with a single graphite-web frontend and a influxdb node as data backend.

We are interesting now in investigate :

a) how to migrate our current  whisper data to influxdb.  Are there any whisper2influx.sh tool ?

 b) how to configure influxdb to get the N different fixed-size database (retentions)  each one with different resolutions  as whisper does, and how to configure xFilesFactor and aggregationMethod.?

This last point is important because we need higher resolutions (1 metric/minute)  last weeks but also we need at least 3 years of data history. We expect about 10/20 million metrics in next months/years, I will be very grateful if we can configure a limited fixed-size data per metric. It will let us to save  storage size.

**Comment by fenkam** [comment]
Hi ,

I  setup graphite on a single machine and hook it with storm (v0.9.5) to collect storm metrics.That run very good!
Then, I also setup influxdb(0.9.5.1) in the same machine. Now I want to use influxdb as graphite backend; that mean that I want to migrate from carbon/whisper to influxdb in order to get all my storm metrics available into an influxdb database.

Please How do I proceed?

Thanks in advance

**Comment by satish-chef** [comment]
> a) not that i know of, should be easy to make one though.
> I've been using https://github.com/graphite-ng/carbon-relay-ng to send realtime data to graphite-whisper and graphite with influx at the same time, running both graphite systems in parrallel for a while gave us an overlap of a few months
> b) use the influxdb sharding spaces feature, new in 0.8, see their docs & mailing list

@Dieterbe   Can we use the same graphite-relay server running carbon-relay-ng to send data to two more Graphite servers which have influx DB as their Graphite DB backend ?
Some background - We are now running graphite-relay nodes in 8 AWS regions which are sending metrics to two Graphite nodes and both have WhisperDB as their backend.  We want to migrate to InfluxDB due to scalability and reliability issue of WhisperDB which is why i have asked this question.
Thanks in Advance.

**Comment by Dieterbe** [comment]
Hi,
I gave up on this project.running influxdb as graphite never really worked well.
You may want to have a look at https://github.com/grafana/metrictank instead.
